### ISSUE TITLE
Any way to encrypt the URL?

### ISSUE THREAD

**Issue by cookiedragon234** [joshdick/miniProxy#102]
I'm trying to encrypt the URL parsed to miniproxy but I dont quite understand the code. Could someone point me to the place in the code where the url to proxy to is found and set so I can then set it to decode it?

**Comment by joshdick** [comment]
I am not sure what you mean by "encrypt" but the proxy reads its URL from more than one place by design. Look at occurrences of `$url` on [these lines](https://github.com/joshdick/miniProxy/blob/23ae85186fa0c71f301891553133e0df1dbef886/miniProxy.php#L261-L311). Given how miniProxy is currently designed, it would be difficult to obfuscate its URL.
