### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Hadjispyrou** [joshdick/miniProxy#108]
I open then miniProxy.php on my wamp server and then it asks for the url. So what happens next? when i insert the url and proxy it nothing happens? Is this wrong ? And if its not this means that this app proxys  urls and then i open those urls from another window and it hides my ip?

**Comment by joshdick** [comment]
Essentially, miniProxy makes a connection to the requested site on your behalf, sitting in between your computer and the destination site. If your server happens to be using the same Internet connection as your personal computer, miniProxy won't "hide" anything.

If nothing happens when you submit miniProxy's URL form, you should make sure your server meets the [prerequisites that the README mentions](https://github.com/joshdick/miniProxy#prerequisites), and you should also check your server error log for clues.

I'm going to close this issue for now since this doesn't seem to be a problem with miniProxy itself, but I'm happy to keep the conversation going here.
