### ISSUE TITLE
File marked as phishing

### ISSUE THREAD

**Issue by digitaldpp** [joshdick/miniProxy#139]
I got the "Deceptive site ahead" warning on my website and my webhost, Bluehost, suspended my account and told me to delete the following phishing malware, miniProxy.php.

**Comment by joshdick** [comment]
miniProxy is not malware, assuming it was downloaded from this GitHub page (in order to guarantee that it hasn’t been maliciously patched by someone.)

Your webhost understandably doesn’t like miniProxy since they could be considered to be liable for any data accessed through the proxy, which is true for all web proxies including miniProxy. 

If you didn’t install miniProxy yourself, your webhost account credentials may have been compromised, and someone may have installed miniProxy on your site without your knowledge, which is an understandable reason for a webhost to take action.

I hope you get everything straightened out with your webhost, but miniProxy is not the issue here.
