### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by petrk94** [joshdick/miniProxy#140]
I have tested it and it works, but how it work?
Which IP address is shown to the website? 
What header get sent with?
How anonymous its working?

A more detailed manual would be fine before its a good idea to use it.

Thanks

**Comment by stackprogramer** [comment]
hi, I had same question, which ip and port for proxy is used?

**Comment by joshdick** [comment]
The requesting IP address sent to websites is the IP of the machine that miniProxy is running on, rather than the end user's (your own) IP. miniProxy acts as a middleman that hides your IP from web servers in most cases.

I feel that a detailed explanation of how web proxies work is beyond the scope of this project, since it is just one specific web proxy of many that are out there, and I feel that one should research what web proxies are and how they work **before** using any web proxy.

That said, this article may help: https://www.lifewire.com/what-is-web-proxy-3481607

**Comment by petrk94** [comment]
@joshdick 
Hi, thanks for the response. Of course I know how a proxy work, but not every github project is worth to use in production, thats why I want to know how it works, because there is no documentation (dont mean the comments in code), where its explained how its working etc.
So Im glad its working, but I want to be sure that the script is doing what it is intended to do.
