### ISSUE TITLE
Need help configuring it with nginx

### ISSUE THREAD

**Issue by theerfan** [joshdick/miniProxy#141]
Hi, I'm trying to configure this proxy on my server using nginx, but apparently I fail to do so because when I try to access my server it shows the main code on GitHub instead of the starting page. (Image attached if that's confusing.)
I think there's something wrong with the way I configured it, but since I have zero experience in php, I don't know what I'm doing wrong.

So what I did was that I cloned [dockerised-php](https://github.com/mikechernev/dockerised-php) and replaced its index.php with this project's miniProxy.php file (renamed to index.php)

Any help would be greatly appreciated, thanks!

![image](https://user-images.githubusercontent.com/11455681/77948509-c44c6780-72da-11ea-98b9-e3fe2e721e5a.png)

**Comment by joshdick** [comment]
If you're seeing the GitHub page, it's likely you saved a copy of the GitHub page rather than miniProxy itself. This is the file you need to save: https://raw.githubusercontent.com/joshdick/miniProxy/master/miniProxy.php

For more details about getting PHP working with nginx, ArchWiki is a great place to start even if you're not running Arch Linux: https://wiki.archlinux.org/index.php/Nginx#PHP_implementation

Beyond that, I unfortunately don't have the time to help debug your specific server setup.

**Comment by theerfan** [comment]
Yes, that was the problem! Thank you.
Sorry for not noticing that, I wasn't able to recognize it because it was saved with the "correct" filename.

**Comment by joshdick** [comment]
I'm glad that did the trick!
