### ISSUE TITLE
External javascript gets mangled

### ISSUE THREAD

**Issue by TerrorFactor** [joshdick/miniProxy#26]
I am trying to use miniProxy with a website that uses dynamic forms. When you select something, the site does a GET request to get the changed fields, and adds them to the current form. 

This does not work in miniProxy. Upon closer inspection, it seems that those external javascripts get mangled, by added html code.

**Comment by joshdick** [comment]
If external scripts are getting mangled with added HTML code (for example, the `<!-- Proxified page constructed by miniProxy -->` comment), it's likely that the scripts are being served with an incorrect `content-type` header, uding the value `text/html` instead of `application/javascript`.

Can you confirm whether this is the case?

**Comment by TerrorFactor** [comment]
I am not really sure how to check the headers of a javascript, but this is the page that I am trying to proxy: http://www2.kapaza.be/nl/ai/
They do get proxified, yes :)

**Comment by etiktin** [comment]
I took a quick look using the network tab of devtools and it seems Josh is correct. Most js files on that site are served with `text/html`.

**Comment by joshdick** [comment]
Thanks @etiktin. This means that the proxy is behaving correctly, but that site/server is not. Right now, I don't want to go as far as having the proxy try to detect the language of the actual received content when the received `content-type` headers are wrong; this edge case would require a disproportionately large amount of work to work around.

**Comment by etiktin** [comment]
Can't we also take into account the extension of the resource? So if it end's with `.js` we'll treat it as JavaScript.

**Comment by TerrorFactor** [comment]
Thank you for clarifying! File extension was also the first thing that came to mind over here.

**Comment by lesander** [comment]
Content type headers were introduced exactly for what this issue turns out to be about: determining the language (type) of the file / content. I think you should contact the people behind that website instead, since it's a fault on their end.

**Comment by TerrorFactor** [comment]
I know, but I doubt that the biggest ad site in Belgium is willing to cooperate with me, so that I can proxy their site :)
A fault is relative, since every browser seems to process things fine. It would be an ideal world if everyone kept to the standards, but we all know that is not the case.

**Comment by lesander** [comment]
@TerrorFactor Is the `<!-- Proxified page constructed by miniProxy -->` comment the only thing that messes up the JavaScript? If so, you can easily remove / disable line 401 from your `miniProxy.php`.

https://github.com/joshdick/miniProxy/blob/master/miniProxy.php#L401

**Comment by TerrorFactor** [comment]
@lesander No, there are more things that are messed up. I'm not at my home pc right now, but I'll verify tonight/tomorrow :)

**Comment by joshdick** [comment]
I don't have a strong defense here :), but trying to detect content type by file extension seems like a slippery slope to me since that list would never really be complete. There's also no guarantee that the actual contents of the file match the content-type header OR extension, though a site would have to go out of the way to be coded wrong if this were the case.

Maybe it's worth adding a generic mechanism for this, similar to the whitelisting mechanism? "Treat all files with X extension as Y content type", rather than explicitly handling this single case?

**Comment by TerrorFactor** [comment]
@joshdick Can't it be detected the same way as a browser detects it? I am guessing a browser just uses the <script>-tags?
My programming knowledge is limited to hacking up/editing some scripts/code, so I might be off quite a bit :)
