### ISSUE TITLE
rel2abs for //urls

### ISSUE THREAD

**Issue by CarlAmbroselli** [joshdick/miniProxy#27]
rel2abs fails for urls like `//geo.query.yahoo.com` in src.

**Comment by joshdick** [comment]
Not sure I understand the issue here.

`//geo.query.yahoo.com` is an absolute URL, so the expected (and current) behavior of `rel2abs()` is that if `//geo.query.yahoo.com` is used as the `$rel` parameter, it shouldn't be modified.

**Comment by etiktin** [comment]
@joshdick, if a url doesn't have a scheme, we treat it as http (see: https://github.com/joshdick/miniProxy/blob/master/miniProxy.php#L186-L188). Shouldn't we  return the url from rel2abs with the scheme of base so if it's https we will preserve it?

**Comment by joshdick** [comment]
@etiktin I thought about this a little bit.

In cases where `$url` was generated by the proxy itself, the URL should already have passed through `rel2abs()`, so I don't think this is an issue, unless there are cases I'm not thinking of.

The code path you highlighted should (in theory!) only ever get hit if the user explicitly supplies a URL starting with `//`. This check is performed since cURL doesn't like being passed URLs that start with `//`. If one *is* explicitly supplied, it shouldn't hurt to treat it like an HTTP URL, but there was a little bit of redundancy in the code that's doing it, so I just pushed 2ac6f8b which cleans it up slightly. :)
