### ISSUE TITLE
Blocked by some site logins

### ISSUE THREAD

**Issue by Jamman** [joshdick/miniProxy#37]
When I try to log in to some pages - social media - it does not let me log in... is this resolvable or a shortcoming of this kind of solution?

> Security notice - For your security, never enter your Facebook password on sites not located on Facebook.com

Also - Is it possible to create a 'blacklist' as well as whitelist?

**Comment by joshdick** [comment]
Because miniProxy does not support cookies, it is not likely to work with most social media sites since nearly all of them rely on cookies. See #24 for more discussion on this.

It is certainly possible to create a blacklist. You can do that by essentially making a 2nd copy of the existing whitelist logic and setting `$urlIsValid = false;` on a match. In the interest of keeping miniProxy small, I'd rather not officially add blacklist functionality at this time.

**Comment by BenNottelling** [comment]
I'd like to point out that if you would like to get onto facebook use the cookie branch and add the following line
`curl_setopt($ch, CURLOPT_HTTPHEADER, array("X-Forwarded-For: $ip"));`
after
```
  //Other cURL options.
  curl_setopt($ch, CURLOPT_HEADER, true);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
```
Then visit the MOBILE page of facebook (m.facebook.com) you can complete the login verification and access facebook! Have fun :D Oh, and P.S. the idea here is that the proxy will attempt to report the users REAL IP, not the server's so you loose that bit of privacy.

**Comment by BenNottelling** [comment]
Okay, I've gone ahead and created an update to MiniProxy to allow getting onto FaceBook, it forces you to use I.E 8 compatible page of website so there are fewer scripts to break, it allows the website to function quite well :D 
It's in my branch Here https://github.com/BenNottelling/miniProxy/tree/BetaMaster
And FaceBook as been confirmed to work from RP https://github.com/BenNottelling/miniProxy/commit/b133479a9783637919bb17ebff8c810eef5cd4b2
