### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Jamman** [joshdick/miniProxy#43]
I was seeing some issues with getting a blank page and sometimes just 'PROXY-IS-ALIVE' , then started seeing some fatal errors
Updated to the latest version and still seeing this error (path altered)

Fatal error: Call to undefined function mb_detect_encoding() in /home/domain/miniProxy.php on line 317

**Comment by Jamman** [comment]
I'm suspecting it is a PHP version issue... It works on one server but not another.

We're also finding issues with Facebook requiring a security password and it doesnt work - their script is domain protected... is there any way around this?  we can load the script, but it wont run... any way of automatically modifying the script to allow it?

**Comment by joshdick** [comment]
Regardless of PHP version, `mb_detect_encoding` won't work if your PHP installation doesn't have the `mbstring` module loaded.

As for Facebook, I'm not sure what you mean by "domain protected" (perhaps [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy))? The proxy does no special handling for CSP and I'm not sure whether manipulating the CSP headers is a good idea since that defeats the very purpose of CSP in the first place. Facebook would still not work even without this problem since miniProxy currently does not support cookies.
