### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Maxie01** [joshdick/miniProxy#50]
`Parse error: syntax error, unexpected T_FUNCTION` on line 180

Did i do something?

**Comment by joshdick** [comment]
This is likely caused by a PHP version incompatibility. What version of PHP are you using?

miniProxy requires PHP version 5.4.7 or later, but it should also show an error if your PHP version is older than that/unsupported. If you're using the latest version of miniProxy with an incompatible PHP version and don't see an error, that's a separate issue with miniProxy.

**Comment by joshdick** [comment]
Closing this due to lack of response, but feel free to continue the conversation any time you'd like!
