### ISSUE TITLE
my simple php http proxy

### ISSUE THREAD

**Issue by pejman-hkh** [joshdick/miniProxy#53]
Hello,
What do think about this : 
https://github.com/pejman-hkh/php-simple-http-proxy/

**Comment by joshdick** [comment]
It's a good start, but I don't see how this is a miniProxy issue?

**Comment by pejman-hkh** [comment]
I don't know too. this is my firsts activity in github. sorry if isn't a miniproxy issue.
My solution for proxy is better than you. In first time i desicde to write a proxy simillar you. find every css and js and every url and proxy it on url.
but in my solution don't need to do that. you config firefox to proxy to an ip and port and every things work very good. ( ajax request, css, js and ... )

**Comment by joshdick** [comment]
Thanks for clarifying.

miniProxy is designed for situations where users aren't able to change browser settings or install a new browser (usually because of restrictions put in place by an outside system administrator.)

Your approach can work in situations where users are able to change the system and/or browser proxy configuration. Additionally, Apache itself can be used as a proxy server, or a SOCKS proxy could be used instead.

**Comment by pejman-hkh** [comment]
Thanks for your answer
