### ISSUE TITLE
Not working with ajax request which return json or plain text

### ISSUE THREAD

**Issue by harryv001** [joshdick/miniProxy#55]
It's adding HTML tags like DOCTYPE, html and body. It adds JavaScript code before actual output which breaks the system.

**Comment by joshdick** [comment]
miniProxy only attempts to add extra elements in cases where the originating web server serves a resource with the MIME type/header `Content-Type: text/html`.

So, if the server is **incorrectly** sending `Content-Type: text/html` with JSON or plain text, you would see this behavior, but this is not an issue with miniProxy.

I tried loading https://resttesttest.com/ in miniProxy and making requests to my ham radio callsign service, http://callook.info, using it. Here are the URLs I made requests to:

https://callook.info/W1AW/text
https://callook.info/W1AW/json

I verified that requests were indeed being sent through the proxy and that the responses were coming through uncorrupted by HTML/as expected.

So, I believe the problem is that the server you are attempting to use with miniProxy is serving the incorrect MIME type `text/html` for JSON and text, and not with miniProxy.
