### ISSUE TITLE
miniProxy does not handle content dynamically added to pages via JavaScript

### ISSUE THREAD

**Issue by aaronorosen** [joshdick/miniProxy#56]
Wanted to ask out of curiosity or if there could potentially be a solution to this problem i'm seeing. Some websites (I just noticed this issue on airbnb.com) that on the page after running through the proxy has the following:

> `<a href='/experiences/4725'>....</a>
`

When i click on that link it doesn't send me to the correct location. I was wondering if this was because this link was placed on the page via javascript after the page has loaded? Is there anyway the proxy can handle this case as well?

**Comment by aaronorosen** [comment]
I think once solution could be injecting some javascript into the page that basically rewrites these links. I think you'd need to call that method in a loop to be able to handle dynamic changes etc to the page.

**Comment by joshdick** [comment]
miniProxy definitely handles relative links in static pages correctly, and AirBnB does indeed appear to dynamically add lots of elements to the page.

This could possibly be solved using [https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver](MutationObserver) instead of a loop, but is a large amount of work since a lot of the proxy logic would have to be duplicated in JavaScript to handle client-side changes.

**Comment by joshdick** [comment]
https://github.com/muicss/sentineljs could also work similarly to `MutationObserver`.

**Comment by coder580** [comment]
can this be fixed
