### ISSUE TITLE
Proxy returns Error 500

### ISSUE THREAD

**Issue by perskes** [joshdick/miniProxy#90]
Installed all the requirements, not I'm faced with a Error 500 everytime I try to reach an URL via the proxy. Any idea?

This is the error!
192.168.0.14 - - [16/OCT/2017:19:30:25 +0200] "GET /index.php?example.com HTTP/1.1" 302 338 "http://192.168.0.50" "Mozilla/5.0 (Windows NT 6.1; Win64; 64) AppleWebKit/537.36 (KTHML, like Gecko) Chrome/61.0.3161.100 Safari/537.36"

Any way to debug this?

**Comment by joshdick** [comment]
Are you accessing miniProxy through another (Apache) proxy? That looks like an Apache log, and if `index.php` is miniProxy, it looks like the proxy is responding with a `302` and not a `500`?

**Comment by perskes** [comment]
Wow, what a fast reply!

I was indeed testing squid before, but I made sure to stop the process and verify that it is not running!
You are right, it's an apache log, and it indeed shows a 302, but the webbrowser gives me a 500.

I checked again and undid everything I did and I still get the error, even in browsers I did not use a proxy on.

At least after deleting a registry key I get a "500" in the apache log!

Still tinkering on it, so if you have any idea what I can try, I'd be glad! 
I'll try it on a fresh VM tomorrow and come back with feedback!

**Comment by Cevastes** [comment]
Did you find a solution? I also getting error 500 in my browser.

**Comment by joshdick** [comment]
@Cevastes If your issue was solved by doing `sudo apt-get install php7.1-xml`, the version of PHP you were using had its XML extension disabled, but it's supposed to be [enabled by default](http://php.net/manual/en/xml.installation.php).

@perskes If you're not seeing any specific PHP error(s), it sounds like an issue with your server configuration and not with miniProxy. If you make a file `test.php` with the contents `<?php phpinfo(); ?>` and try to access it on your server, does that work?

**Comment by robin-moser** [comment]
With PHP 7.0 running on an Nginx, installing the XML extension with `sudo apt-get install php7.0-xml` worked for me.
