### ISSUE TITLE
Add support for twitch.tv?

### ISSUE THREAD

**Issue by GGrandma** [joshdick/miniProxy#98]
Whenever visiting twitch.tv an error shows up saying “Failed to load module”

**Comment by joshdick** [comment]
This is just a guess, but it looks like this happens because the page attempts to load assets dynamically via JavaScript which bypasses the proxy (see #56), and then loading fails due to [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) violations because the proxied page doesn't match the location that the dynamically-loaded assets are served from.

Closing as a duplicate of #56.
